Repository opal/opal, pull requests merged in 2019-09, with the labels that each got.

#2011 Remove workaround targeted at JRuby 1.7
  lib/opal/cli_runners/applescript.rb
  lib/opal/cli_runners/nashorn.rb
  lib/opal/cli_runners/nodejs.rb
Labels: jruby

#2012 Remove legacy runner API
  .travis.yml
  lib/opal/cli_runners.rb
  lib/opal/cli_runners/applescript.rb
  lib/opal/cli_runners/chrome.rb
  lib/opal/cli_runners/nashorn.rb
  lib/opal/cli_runners/nodejs.rb
  lib/opal/cli_runners/server.rb
  lib/opal/cli_runners/system_runner.rb
Labels: cli, refactoring

#2013 Used parser version is incompatible with rubocop
  Gemfile
  UNRELEASED.md
  opal.gemspec
Labels: parser
