Repository opal/opal, pull requests merged in 2019-01, with the labels that each got.

#1926 Fix JRuby build on master
  opal.gemspec
Labels: work-in-progress

#1928 Resolves #1923 Implement ENV.key? in Node.js
  UNRELEASED.md
  stdlib/nodejs.rb
  stdlib/nodejs/env.rb
  stdlib/nodejs/kernel.rb
  tasks/testing.rake
  test/nodejs/test_env.rb
Labels: work-in-progress

#1935 Fix ||= on constants
  lib/opal/rewriters/logical_operator_assignment.rb
  spec/filters/bugs/language.rb
  spec/lib/rewriters/logical_operator_assignment_spec.rb
Labels: compiler, language

#1930 Move Kernel#format (and sprintf alias) to a dedicated file
  UNRELEASED.md
  opal/corelib/kernel.rb
  opal/corelib/kernel/format.rb
  opal/opal.rb
Labels: compiled-size, performance
