Repository opal/opal, pull requests merged in 2025-01, with the labels that each got.

#2722 Fix `Module#include` after `#prepend`
  opal/corelib/runtime.js
  spec/opal/core/module/include_spec.rb
Labels: stable-backport

#2697 Let opal build standalone applications via the --compile-to-exe option
  examples/exe/create_apps.sh
  examples/exe/simple.rb
  lib/opal/cli.rb
  lib/opal/cli_options.rb
  lib/opal/exe_compiler.rb
Labels: ready to merge

#2720 Implement EUCJP, JIS and SJIS encodings, add Encoding#decode(io_buffer)
  docs/encoding.md
  opal/corelib/string/encoding.rb
  opal/corelib/string/encoding/dummy.rb
  opal/corelib/string/encoding/eucjp.rb
  opal/corelib/string/encoding/jis.rb
  opal/corelib/string/encoding/sjis.rb
  opal/corelib/string/encoding/tables/generators/generate-source.js
  opal/corelib/string/encoding/tables/generators/generate.js
  opal/corelib/string/encoding/tables/generators/linereader.js
  opal/corelib/string/encoding/tables/generators/sources/CP932-ADD.TXT
  opal/corelib/string/encoding/tables/generators/sources/CP932-IBM-OVERRIDE.TXT
  opal/corelib/string/encoding/tables/generators/sources/CP932-NEC-OVERRIDE.TXT
  opal/corelib/string/encoding/tables/generators/sources/CP932.TXT
  opal/corelib/string/encoding/tables/generators/sources/JIS0201.TXT
  opal/corelib/string/encoding/tables/generators/sources/JIS0208-ADD.TXT
  opal/corelib/string/encoding/tables/generators/sources/JIS0208-IBM.TXT
  opal/corelib/string/encoding/tables/generators/sources/JIS0208-NEC.TXT
  opal/corelib/string/encoding/tables/generators/sources/JIS0208.TXT
  opal/corelib/string/encoding/tables/generators/sources/JIS0212-ADD.TXT
  opal/corelib/string/encoding/tables/generators/sources/JIS0212.TXT
  opal/corelib/string/encoding/tables/generators/sources/NON-ROUND-TRIP.TXT
  opal/corelib/string/encoding/tables/generators/sources/memo.txt
  opal/corelib/string/encoding/tables/jis_ext_inverted.rb
  opal/corelib/string/encoding/tables/jis_inverted.rb
  opal/corelib/string/encoding/tables/sjis_inverted.rb
  opal/opal/full.rb
Labels: priority, ready to merge

#2724 Add Ruby LSP to the gemfile
  Gemfile
Labels: stable-backport

#2727 nodes/if: Require Thread shim
  .rubocop.yml
  lib/opal/nodes/if.rb
Labels: stable-backport, ready to merge

#2719 Runtime split
  lib/opal/cli_runners/source-map-support-browser.js
  lib/opal/cli_runners/source-map-support-node.js
  lib/opal/cli_runners/source-map-support.js
  lib/opal/compiler.rb
  lib/opal/nodes/args/arity_check.rb
  lib/opal/nodes/constants.rb
  lib/opal/nodes/defs.rb
  lib/opal/nodes/module.rb
  opal/corelib/binding.rb
  opal/corelib/error.rb
  opal/corelib/kernel.rb
  opal/corelib/module.rb
  opal/corelib/runtime.js
  opal/corelib/runtime.rb
  opal/opal/base.rb
  opal/runtime/array.rb
  opal/runtime/boot.js
  opal/runtime/bridge.rb
  opal/runtime/class.rb
  opal/runtime/const.rb
  opal/runtime/exception.rb
  opal/runtime/freeze.rb
  opal/runtime/hash.rb
  opal/runtime/helpers.rb
  opal/runtime/method.rb
  opal/runtime/method_missing.rb
  opal/runtime/misc.rb
  opal/runtime/module.rb
  opal/runtime/op_helpers.rb
  opal/runtime/proc.rb
  opal/runtime/regexp.rb
  opal/runtime/runtime.rb
  opal/runtime/send.rb
  opal/runtime/string.rb
  opal/runtime/variables.rb
  spec/filters/bugs/binding.rb
  spec/filters/bugs/kernel.rb
  spec/lib/builder_spec.rb
  stdlib/native.rb
  tasks/performance.rake
Labels: ready to merge
